eHRMS/Areas/HR/Models/CompanyBank.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eHRMS.Areas.HR.Models
{
    public class CompanyBank
    {
        public int CompanyBankID { get; set; }
        [Required]
        public string BankName { get; set; }
        [Required]
        public string BranchName { get; set; }
        [Required]
        public string BranchAddress { get; set; }
        [Required]
        public string AccountNumber { get; set; }
        [Required]
        public string SignAuthority { get; set; }
        [Required]
        public string IFSCCode { get; set; }
        public string FK_CompanyRegistrationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}

eHRMS/Areas/HR/Models/CompanyLocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eHRMS.Areas.HR.Models
{
    public class CompanyLocation
    {
        public int OfficeLocationID { get; set; }
        [Required]
        public string OfficeType { get; set; }
        [Required]
        public string OfficeCode { get; set; }
        [Required]
        public string ContactPerson { get; set; }
        [Required]
        public Nullable<decimal> ContactNo { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$")]
        public string Email { get; set; }
        public Nullable<decimal> FAX { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string TimeZone { get; set; }
        public string FK_CompanyRegistrationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}

eHRMS/Areas/HR/Models/CompanyStatutory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eHRMS.Areas.HR.Models
{
    public class CompanyStatutory
    {
        public int CompanyStatutoryID { get; set; }
        [Required]
        public string TAN { get; set; }
        [Required]
        public string PAN { get; set; }
        [Required]
        public Nullable<bool> ESIApplicable { get; set; }
        public string ESINumber { get; set; }
        [Required]
        public Nullable<bool> PTApplicable { get; set; }
        public string PTNumber { get; set; }
        [Required]
        public Nullable<bool> PFApplicable { get; set; }
        public string PFNumber { get; set; }
        public string FK_CompanyRegistrationID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}

eHRMS/Areas/HR/Controllers/HRCompanyController.cs
using eHRMS.Models;
using eHRMS.Areas.HR.Models;
using eHRMS.Repository;
using eHRMS.Global;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Net;
using System.Data.Entity;
using System.Web.UI;
using System.IO;
using System.Drawing;
using System.Text;
using System.Drawing.Drawing2D;
using System.Collections.ObjectModel;

namespace eHRMS.Areas.HR.Controllers
{
    public class HRCompanyController : Controller
    {
        
        eHRMSEntities context = new eHRMSEntities();
        GlobalFunction objglobal = new GlobalFunction();
        ErrorHandlerClass objError = new ErrorHandlerClass();
        // GET: HR/HRCompany
        [SessionAuthorizeFilter((int)AppsConstants.UserRole.HR)]
        public ActionResult Company_Details(CompanyProfile SubsTbl)
        {
            SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
            try
            {
                SubsTbl = context.tbl_CompanyProfile.Where(x => x.IsActive == true && x.FK_CompanyRegistrationID == objSubs.FK_CompanyRegistrationID).Select(s => new CompanyProfile
                {
                    CompanyName = s.CompanyName,
                    CompanyDetails = s.CompanyDetails,
                    CompanyType = s.CompanyType,
                    CompanyWebsite = s.CompanyWebsite,
                    IndustryType = s.IndustryType,
                    BannerImagePath = s.BannerImagePath,
                    IncorporationDate = s.IncorporationDate,
                    FK_CompanyRegistrationID = s.FK_CompanyRegistrationID,
                    IsActive = s.IsActive,
                }).FirstOrDefault();
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
            }
            return View(SubsTbl);
        }

        [SessionAuthorizeFilter((int)AppsConstants.UserRole.HR)]
        public PartialViewResult Company_Details_View(CompanyProfile SubsTbl)
        {
            SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
            try
            {
                SubsTbl = context.tbl_CompanyProfile.Where(x => x.IsActive == true && x.FK_CompanyRegistrationID == objSubs.FK_CompanyRegistrationID).Select(s => new CompanyProfile
                {
                    CompanyName = s.CompanyName,
                    CompanyDetails = s.CompanyDetails,
                    CompanyType = s.CompanyType,
                    CompanyWebsite = s.CompanyWebsite,
                    IndustryType = s.IndustryType,
                    BannerImagePath = s.BannerImagePath,
                    IncorporationDate = s.IncorporationDate,
                    FK_CompanyRegistrationID = s.FK_CompanyRegistrationID,
                    IsActive = s.IsActive,
                }).FirstOrDefault();
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
            }
            return PartialView(SubsTbl);
        }

        [HttpPost]
        public ActionResult Company_Details(CompanyProfile model, HttpPostedFileBase file)
        {
            try
            {
                SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
                if (ModelState.IsValid && file != null)
                {
                    // Upload Image
                    bool flag = false;
                    Stream stream = file.InputStream;
                    Bitmap sourceImage = new Bitmap(stream);
                    string myfile = string.Empty;
                    var allowedExtensions = new[] { ".JPG", ".PNG", ".GIFS", ".JPEG" };
                    var ext = Path.GetExtension(file.FileName).ToUpper();
                    if (allowedExtensions.Contains(ext))
                    {
                        myfile = "Banner-" + objSubs.FK_CompanyRegistrationID + ext;
                        //resize the image
                        int smallImageHeight = 268;
                        int smallImageWidth = 687;
                        System.Drawing.Image resizedImage = new System.Drawing.Bitmap(smallImageWidth, smallImageHeight, System.Drawing.Imaging.PixelFormat.Format16bppRgb555);
                        Graphics gr = Graphics.FromImage(resizedImage);
                        gr.InterpolationMode = InterpolationMode.HighQualityBicubic;
                        gr.DrawImage(sourceImage, 0, 0, smallImageWidth, smallImageHeight);
                        var path = Path.Combine(Server.MapPath("~/Content/hrms_images/CompanyBanner"), myfile);
                        resizedImage.Save(path);
                        flag = true;
                    }
                    else
                    {
                        ViewBag.ErrorMsg = "Please choose only Image file";
                    }
                    // End Image Upload
                    if (flag)
                    {
                        if (!context.tbl_CompanyProfile.Any(x => x.IsActive == true && x.FK_CompanyRegistrationID == objSubs.FK_CompanyRegistrationID))
                        {
                            SaveDetails(model, myfile);
                            ViewBag.SuccessMsg = "Data saved successfully !";
                            //ModelState.Clear();
                            return View();
                        }
                        else
                        {
                            UpdateDetails(model, myfile);
                            ViewBag.SuccessMsg = "Data updated successfully !";
                            //ModelState.Clear();
                            return View();
                        }

                    }
                    return View();
                }
                else
                {
                    ViewBag.ErrorMsg = "Required fields cannot be blank !";
                    return View();
                }
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
                return View();
            }
        }


        #region Saving Details
        private void SaveDetails(CompanyProfile model, string myfile)
        {
            try
            {
                SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
                tbl_CompanyProfile objCmpPrfl = new tbl_CompanyProfile()
                {
                    CompanyName = model.CompanyName,
                    CompanyDetails = model.CompanyDetails,
                    CompanyType = model.CompanyType,
                    CompanyWebsite = model.CompanyWebsite,
                    IndustryType = model.IndustryType,
                    BannerImagePath = myfile,
                    IncorporationDate = model.IncorporationDate,
                    FK_CompanyRegistrationID = objSubs.FK_CompanyRegistrationID,
                    IsActive = true,
                    CreatedOn = objglobal.TimeZone(objglobal.getTimeZone()),
                    CreatedBy = objSubs.Username
                };
                context.tbl_CompanyProfile.Add(objCmpPrfl);
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
            }
        }
        #endregion

        #region Update Details
        private void UpdateDetails(CompanyProfile model, string myfile)
        {
            try
            {
                SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
                tbl_CompanyProfile Profiledetails = context.tbl_CompanyProfile.Where(x => x.IsActive == true && x.FK_CompanyRegistrationID == objSubs.FK_CompanyRegistrationID).FirstOrDefault();

                Profiledetails.CompanyName = model.CompanyName;
                Profiledetails.CompanyDetails = model.CompanyDetails;
                Profiledetails.CompanyType = model.CompanyType;
                Profiledetails.CompanyWebsite = model.CompanyWebsite;
                Profiledetails.IndustryType = model.IndustryType;
                Profiledetails.BannerImagePath = myfile;
                Profiledetails.IncorporationDate = model.IncorporationDate;
                Profiledetails.UpdatedOn = objglobal.TimeZone(objglobal.getTimeZone());
                Profiledetails.UpdatedBy = objSubs.Username;
                context.Entry(Profiledetails).State = EntityState.Modified;
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
            }
        }
        #endregion

        [SessionAuthorizeFilter((int)AppsConstants.UserRole.HR)]
        public ActionResult Company_Location()
        {
            SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
            List<CompanyLocation> LocationList = new List<CompanyLocation>();
            try
            {
                LocationList = context.tbl_CompanyLocation.Where(x => x.IsActive == true && x.FK_CompanyRegistrationID == objSubs.FK_CompanyRegistrationID).Select(s => new CompanyLocation
                {
                    OfficeLocationID = s.OfficeLocationID,
                    OfficeType = s.OfficeType,
                    OfficeCode = s.OfficeCode,
                    ContactPerson = s.ContactPerson,
                    ContactNo = s.ContactNo,
                    Email = s.Email,
                    Address = s.OfficeAddress,
                }).ToList();
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
                ViewBag.ErrorMsg = "Something went wrong !";
            }
            return View(LocationList);
        }

        [SessionAuthorizeFilter((int)AppsConstants.UserRole.HR)]
        public ActionResult Company_Location_Create(string id)
        {
            ViewData["AllTimeZoneList"] = AllTimeZoneList();
            if (id != null)
            {
                id = HttpUtility.UrlDecode(id);

eHRMS/Areas/HR/Views/HRCompany/Company_Bank.cshtml
@model IEnumerable<eHRMS.Areas.HR.Models.CompanyBank>
@{
    ViewBag.Title = "Company Bank Details";
    ViewBag.Now = "Company Management / Company Bank Details";
    Layout = "~/Areas/HR/Views/Shared/_LayoutPageHR.cshtml";
}

@if (ViewBag.SuccessMsg != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Well done!</strong> @ViewBag.SuccessMsg
    </div>
}
@if (ViewBag.ErrorMsg != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Oh snap!</strong> @ViewBag.ErrorMsg
    </div>
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" onclick="location.href = '@Url.Action("Company_Bank_Create", "HRCompany", new { area = "HR" })';">Add New</button>
                </div>
                <h2 class="panel-title">Statutory Details</h2>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-default">
                    <thead>
                        <tr>
                            <th>BANK NAME</th>
                            <th>BRANCH NAME</th>
                            <th>IFSC CODE</th>
                            <th>ACCOUNT NO</th>
                            <th>SIGN AUTHORITY</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    @if (Model.Count() > 0)
                    {
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="gradeX">
                                    <td>@item.BankName</td>
                                    <td>@item.BranchName</td>
                                    <td>@item.IFSCCode</td>
                                    <td>@item.AccountNumber</td>
                                    <td>@item.SignAuthority</td>
                                    <td>
                                        <a href="@Url.Action("Company_Bank_Create", "HRCompany", new { area = "HR", id = HttpUtility.UrlEncode(item.CompanyBankID.ToString()) })"><i class="fa fa-pencil-square-o"></i></a>
                                        |
                                        <a href="" onclick="DeletePermanently(@item.CompanyBankID)"><i class=" fa fa-trash-o"></i></a>
                                        @*<input id="CompanyBankID" value="@item.CompanyBankID" type="hidden" />*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    }
                </table>
            </div>
        </section>
    </div>
</div>

<script type="text/javascript">
    
    function DeletePermanently(CompanyBankID) {
        //var id = $("#CompanyBankID").val();
        var id = CompanyBankID;
        $.ajax({
            type: "POST",
            url: "/HRCompany/DeleteBank?CompanyBankID=" + id,
            dataType: "JSON",
            success: function (result) {                
                alert("Bank details deleted successfully !");
            }
        });
    }
</script>

eHRMS/Areas/HR/Views/HRCompany/Company_Bank_Create.cshtml
@model eHRMS.Areas.HR.Models.CompanyBank
@{
    ViewBag.Title = "Company Bank";
    ViewBag.Now = "Company Management / Add Bank Details";
    Layout = "~/Areas/HR/Views/Shared/_LayoutPageHR.cshtml";
}
@using (Html.BeginForm("Company_Bank_Create", "HRCompany", FormMethod.Post))
{
    if (ViewBag.SuccessMsg != null)
    {
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong>Well done!</strong> @ViewBag.SuccessMsg
        </div>
    }
    if (ViewBag.ErrorMsg != null)
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong>Oh snap!</strong> @ViewBag.ErrorMsg
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" onclick="location.href = '@Url.Action("Company_Bank", "HRCompany", new { area = "HR" })';">View All</button>
                        @*<a href="#" class="fa fa-caret-down"></a>*@
                        <!--<a href="#" class="fa fa-times"></a>-->
                    </div>
                    <h2 class="panel-title">Add Bank Detail</h2>
                </header>
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Bank Name <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-university"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.BankName, new { @class = "form-control", placeholder = "Bank Name" })
                                    @*<input type="text" class="form-control" placeholder="Bank Name">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Branch Name <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-home"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.BranchName, new { @class = "form-control", placeholder = "Branch Name" })
                                    @*<input type="text" class="form-control" placeholder="Branch Name">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Branch Address <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-map-marker"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.BranchAddress, new { @class = "form-control", placeholder = "Branch Address" })
                                    @*<input type="text" class="form-control" placeholder="Branch Address">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Account No <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-key"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.AccountNumber, new { @class = "form-control", placeholder = "Account No" })
                                    @*<input type="text" class="form-control" placeholder="Account No">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Sign Authority <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-user"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.SignAuthority, new { @class = "form-control", placeholder = "Sign Authority" })
                                    @*<input type="text" class="form-control" placeholder="Sign Authority">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">IFSC Code <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-pencil"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.IFSCCode, new { @class = "form-control", placeholder = "IFSC Code" })
                                    @*<input type="text" class="form-control" placeholder="IFSC Code">*@
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <footer class="panel-footer center">
                    <button type="submit" class="mb-xs mt-xs mr-xs btn btn-success">Add</button>
                    <button type="button" onclick="location.href = '@Url.Action("Company_Details", "HRCompany", new { area = "HR" })';" class="mb-xs mt-xs mr-xs btn btn-danger">Cancel</button>
                </footer>
            </section>
        </div>
    </div>
}

eHRMS/Areas/HR/Views/HRCompany/Company_Location.cshtml
@model IEnumerable<eHRMS.Areas.HR.Models.CompanyLocation>
@{
    ViewBag.Title = "Company Location Details";
    ViewBag.Now = "Company Management / Company Location Details";
    Layout = "~/Areas/HR/Views/Shared/_LayoutPageHR.cshtml";
}
@if (ViewBag.SuccessMsg != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Well done!</strong> @ViewBag.SuccessMsg
    </div>
}
@if (ViewBag.ErrorMsg != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Oh snap!</strong> @ViewBag.ErrorMsg
    </div>
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" onclick="location.href = '@Url.Action("Company_Location_Create", "HRCompany", new { area = "HR" })';">Add New</button>
                </div>

                <h2 class="panel-title">Location Details</h2>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-default">
                    <thead>
                        <tr>
                            <th>Office Type</th>
                            <th>Office Code</th>
                            <th>ContactPerson</th>
                            <th>Email</th>
                            <th>Contact Number</th>
                            <th>Address</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    @if (Model.Count() > 0)
                    {
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="gradeC">
                                    <td>@item.OfficeType</td>
                                    <td>@item.OfficeCode</td>
                                    <td>@item.ContactPerson</td>
                                    <td>@item.Email</td>
                                    <td>@item.ContactNo</td>
                                    <td>@item.Address</td>
                                    <td>
                                        <a href="@Url.Action("Company_Location_Create", "HRCompany", new { area = "HR", id = HttpUtility.UrlEncode(item.OfficeLocationID.ToString()) })"><i class="fa fa-pencil-square-o"></i></a>
                                        |
                                        <a href="" onclick="DeletePermanently(@item.OfficeLocationID)"><i class="fa fa-trash-o"></i></a>
                                        @*<input id="OfficeLocationID" value="@item.OfficeLocationID" type="hidden" />*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    }
                </table>
            </div>
        </section>
    </div>
</div>

<script type="text/javascript">
    function DeletePermanently(OfficeLocationID) {
        //var id = $("#OfficeLocationID").val();
        var id = OfficeLocationID;
        $.ajax({
            type: "POST",
            url: "/HRCompany/DeleteLocation?OfficeLocationID=" + id,
            dataType: "JSON",
            success: function (result) {
                alert("Office Location deleted successfully !");
            }
        });
    }
</script>

eHRMS/Areas/HR/Views/HRCompany/Company_Statutory.cshtml
@model IEnumerable<eHRMS.Areas.HR.Models.CompanyStatutory>
@{
    ViewBag.Title = "Company Statutory Details";
    ViewBag.Now = "Company Management / Company Statutory Details";
    Layout = "~/Areas/HR/Views/Shared/_LayoutPageHR.cshtml";
}
@if (ViewBag.SuccessMsg != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Well done!</strong> @ViewBag.SuccessMsg
    </div>
}
@if (ViewBag.ErrorMsg != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Oh snap!</strong> @ViewBag.ErrorMsg
    </div>
}
<div class="row">
    <div class="col-lg-12">

        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" onclick="location.href = '@Url.Action("Company_Statutory_Create", "HRCompany", new { area = "HR" })';">Add New</button>
                </div>
                <h2 class="panel-title">Statutory Details</h2>
            </header>
            <div class="panel-body">
                <table class="table table-bordered table-striped mb-none" id="datatable-default">
                    <thead>
                        <tr>
                            <th>TAN No.</th>
                            <th>PAN No.</th>
                            <th>ESI No.</th>
                            <th>PT No.</th>
                            <th>PF No.</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    @if (Model.Count() > 0)
                    {
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="gradeC">
                                    <td>@item.TAN</td>
                                    <td>@item.PAN</td>
                                    <td>@item.ESINumber</td>
                                    <td>@item.PTNumber</td>
                                    <td>@item.PFNumber</td>
                                    <td>
                                        <a href="@Url.Action("Company_Statutory_Create", "HRCompany", new { area = "HR", id = HttpUtility.UrlEncode(item.CompanyStatutoryID.ToString()) })"><i class="fa fa-pencil-square-o"></i></a>
                                        |
                                        <a href="" onclick="DeletePermanently(@item.CompanyStatutoryID)"><i class=" fa fa-trash-o"></i></a>
                                        @*<input id="OfficeStatutoryID" value="@item.CompanyStatutoryID" type="hidden" />*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    }
                </table>
            </div>
        </section>
    </div>
</div>

<script type="text/javascript">
    function DeletePermanently(CompanyStatutoryID) {
        //var id = $("#OfficeStatutoryID").val();
        var id = CompanyStatutoryID;
        $.ajax({
            type: "POST",
            url: "/HRCompany/DeleteStatutory?OfficeStatutoryID=" + id,
            dataType: "JSON",
            success: function (result) {
                alert("Company Statutory deleted successfully !");
            }
        });
    }
</script>