eHRMS/Controllers/DesignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eHRMS.Areas.Admin.Controllers
{
    public class DesignController : Controller
    {
        // GET: Admin/AdminDesign
        public ActionResult Header()
        {
            return View();
        }


        //
        // GET: /Navmene/

        public ActionResult Navmenu()
        {
            return View();
        }

        //
        // GET: /Rightside/

        public ActionResult Rightside()
        {
            return View();
        }
    }
}

eHRMS/Controllers/MasterDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eHRMS.Global;

namespace eHRMS.Controllers
{
    public class MasterDashboardController : Controller
    {
        // GET: MasterDashboard
        [SessionAuthorizeFilter((int)AppsConstants.UserRole.MasterAdmin)]
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

eHRMS/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html class="fixed sidebar-left-collapsed">

<head>
    <!-- Basic -->
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>
    <meta name="keywords" content="eHRMS Application" />
    <meta name="description" content="eHRMS - ESTAR SOFTWARRE SOLUTION PVT. LTD.">
    <meta name="author" content="estarsoftwaresolution.com">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    @*<link rel="shortcut icon" href="~/Images/bullet.png" />*@
    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Content/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="~/Content/assets/vendor/select2/select2.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/jquery-datatables-bs3/assets/css/datatables.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/skins/default.css" />

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/theme-custom.css">

    <!-- Head Libs -->
    <script src="~/Content/assets/vendor/modernizr/modernizr.js"></script>

</head>
<body>
    <!-- start: page -->
    <section class="body">
        <!-- start: header -->
        @Html.Action("Header", "Design", new { area = "" })
        <!-- end: header -->
        <div class="inner-wrapper">
            <!-- start: sidebar -->
            @Html.Action("Navmenu", "Design", new { area = "" })
            <!-- end: sidebar -->
            <section role="main" class="content-body">
                <header class="page-header">
                    <h2>@ViewBag.Title</h2>
                    <div class="right-wrapper pull-right">
                        <ol class="breadcrumbs">
                            <li>
                                <a href="@Url.Action("Dashboard", "MasterDashboard", new { area = "" })">
                                    <i class="fa fa-home"></i>
                                </a>
                            </li>
                            <li><span>@ViewBag.Now</span></li>
                        </ol>

                        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
                    </div>
                </header>

                <!-- Body Section -->
                @RenderBody()
                <!-- End Body Section -->

            </section>
        </div>
        @Html.Action("Rightside", "Design", new { area = "" }))
    </section>

    <!-- end: page -->
    <!-- Vendor -->
    <script src="~/Content/assets/vendor/jquery/jquery.js"></script>
    <script src="~/Content/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/Content/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/Content/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="~/Content/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="~/Content/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Specific Page Vendor -->
    <script src="~/Content/assets/vendor/select2/select2.js"></script>
    <script src="~/Content/assets/vendor/jquery-datatables/media/js/jquery.dataTables.js"></script>
    <script src="~/Content/assets/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js"></script>
    <script src="~/Content/assets/vendor/jquery-datatables-bs3/assets/js/datatables.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="~/Content/assets/javascripts/theme.js"></script>

    <!-- Theme Custom -->
    <script src="~/Content/assets/javascripts/theme.custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/Content/assets/javascripts/theme.init.js"></script>


    <!-- Examples -->
    <script src="~/Content/assets/javascripts/tables/examples.datatables.default.js"></script>
    <script src="~/Content/assets/javascripts/tables/examples.datatables.row.with.details.js"></script>
    <script src="~/Content/assets/javascripts/tables/examples.datatables.tabletools.js"></script>

</body>
</html>

eHRMS/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE html>
<html class="fixed">

<head>
    <!-- Basic -->
    <meta charset="UTF-8">
    <title>@ViewBag.Title</title>
    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="Porto Admin - Responsive HTML5 Template">
    <meta name="author" content="okler.net">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    @*<link rel="shortcut icon" href="~/Images/bullet.png" />*@
    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Content/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />
    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="~/Content/assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
    <link rel="stylesheet" href="~/Content/assets/vendor/morris/morris.css" />
    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/theme.css" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/skins/default.css" />
    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/theme-custom.css">
    <!-- TreeView CSS -->
    <link href="~/Content/assets/CSS3Treeview/styles/CSS3Treeview.css" rel="stylesheet" />
    <!-- Head Libs -->
    <script src="~/Content/assets/vendor/modernizr/modernizr.js"></script>

    <!-- Checkbox Selecct All -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#selecctall').click(function (event) {  //on click
                if (this.checked) { // check select status
                    $('.checkbox1').each(function () { //loop through each checkbox
                        this.checked = true;  //select all checkboxes with class "checkbox1"
                    });
                } else {
                    $('.checkbox1').each(function () { //loop through each checkbox
                        this.checked = false; //deselect all checkboxes with class "checkbox1"
                    });
                }
            });

        });
    </script>

    <style type="text/css">
        .loader {
            position: fixed;
            left: 0px;
            top: 0px;
            width: 100%;
            height: 100%;
            z-index: 9999;
            background: url('../Content/assets/images/loading.gif') 50% 50% no-repeat rgb(249,249,249);
        }
    </style>
    <script src="ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>



    <script type="text/javascript">
        $(window).load(function () {
            $(".loader").fadeOut("slow");
        });
    </script>

</head>
<body>
    <div class="loader"></div>
    <!-- Body Section -->
    @RenderBody()
    <!-- End Body Section -->
    <!-- Vendor -->
    <script src="~/Content/assets/vendor/jquery/jquery.js"></script>
    <script src="~/Content/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/Content/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/Content/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="~/Content/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="~/Content/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Specific Page Vendor -->
    <script src="~/Content/assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
    <script src="~/Content/assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
    <script src="~/Content/assets/vendor/jquery-appear/jquery.appear.js"></script>
    <script src="~/Content/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
    <script src="~/Content/assets/vendor/jquery-easypiechart/jquery.easypiechart.js"></script>
    <script src="~/Content/assets/vendor/flot/jquery.flot.js"></script>
    <script src="~/Content/assets/vendor/flot-tooltip/jquery.flot.tooltip.js"></script>
    <script src="~/Content/assets/vendor/flot/jquery.flot.pie.js"></script>
    <script src="~/Content/assets/vendor/flot/jquery.flot.categories.js"></script>
    <script src="~/Content/assets/vendor/flot/jquery.flot.resize.js"></script>
    <script src="~/Content/assets/vendor/jquery-sparkline/jquery.sparkline.js"></script>
    <script src="~/Content/assets/vendor/raphael/raphael.js"></script>
    <script src="~/Content/assets/vendor/morris/morris.js"></script>
    <script src="~/Content/assets/vendor/gauge/gauge.js"></script>
    <script src="~/Content/assets/vendor/snap-svg/snap.svg.js"></script>
    <script src="~/Content/assets/vendor/liquid-meter/liquid.meter.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/jquery.vmap.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/data/jquery.vmap.sampledata.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/jquery.vmap.world.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/continents/jquery.vmap.africa.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/continents/jquery.vmap.asia.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/continents/jquery.vmap.australia.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/continents/jquery.vmap.europe.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/continents/jquery.vmap.north-america.js"></script>
    <script src="~/Content/assets/vendor/jqvmap/maps/continents/jquery.vmap.south-america.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="~/Content/assets/javascripts/theme.js"></script>
    <!-- Theme Custom -->
    <script src="~/Content/assets/javascripts/theme.custom.js"></script>
    <!-- Theme Initialization Files -->
    <script src="~/Content/assets/javascripts/theme.init.js"></script>
    <!-- Examples -->
    <script src="~/Content/assets/javascripts/dashboard/examples.dashboard.js"></script>
</body>
</html>