eHRMS/Areas/Admin/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eHRMS.Areas.Admin.Models
{
    public class ChangePassword
    {
        public string UserID { get; set; }
        [Required]
        public string CurrentPassword { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Confirm_Password { get; set; }
    }
}

eHRMS/Areas/Employee/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eHRMS.Areas.Employee.Models
{
    public class ChangePassword
    {
        public string UserID { get; set; }
        [Required]
        public string CurrentPassword { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Confirm_Password { get; set; }
    }
}

eHRMS/Areas/HR/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eHRMS.Areas.HR.Models
{
    public class ChangePassword
    {
        public string UserID { get; set; }
        [Required]
        public string CurrentPassword { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string Confirm_Password { get; set; }
    }
}

eHRMS/Areas/Admin/Controllers/AdminAccountController.cs
using eHRMS.Areas.Admin.Models;
using eHRMS.Global;
using eHRMS.Models;
using eHRMS.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace eHRMS.Areas.Admin.Controllers
{
    public class AdminAccountController : Controller
    {
        eHRMSEntities context = new eHRMSEntities();
        GlobalFunction objglobal = new GlobalFunction();
        ErrorHandlerClass objError = new ErrorHandlerClass();
        // GET: Admin/AdminAccount

        [SessionAuthorizeFilter((int)AppsConstants.UserRole.Admin)]
        public ActionResult ChangePassword()
        {
            SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
            ChangePassword objlist = new ChangePassword();
            objlist.UserID = objSubs.Username;
            return View(objlist);
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePassword model)
        {
            SubscriptionModel objSubs = objglobal.GetSubscriptionDetails();
            model.UserID = objSubs.Username;
            try
            {
                if (ModelState.IsValid)
                {
                    if(model.Password==model.Confirm_Password)
                    {
                        string crntpass = objglobal.Encrypt(model.CurrentPassword);
                        tbl_Login objlogin = context.tbl_Login.Where(x => x.IsActive == true && x.FK_CompanyRegistrationID == objSubs.FK_CompanyRegistrationID && x.Username == model.UserID).FirstOrDefault();
                        if (objlogin.Password == crntpass)
                        {
                            objlogin.Password = objglobal.Encrypt(model.Password);
                            objlogin.UpdatedOn = System.DateTime.Now;
                            objlogin.UpdatedBy = objSubs.Username;
                            context.Entry(objlogin).State = EntityState.Modified;
                            context.SaveChanges();
                            ViewBag.SuccessMsg = "Password updated successfully !";
                        }
                        else
                        {
                            ViewBag.ErrorMsg = "Current Password you have entered is wrong !";
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMsg = "New Passwords did not match !";
                    }
                    
                    return View(model);
                }
                else
                {
                    ViewBag.ErrorMsg = "Required fields cannot be blank or Please enter valid credentials !";
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                objError.LogError(ex);
                return View(model);
            }
        }



        #region LogOut
        [HttpGet]
        public ActionResult LogOut()
        {
            Session["User_ID"] = null;
            Session["ContactPerson"] = null;
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            FormsAuthentication.SignOut();

            Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();
            Session.Abandon();

            return RedirectToAction("SignIn", "Account", new { area = "" });
        }
        #endregion
    }
}

eHRMS/Areas/Admin/Views/AdminAccount/ChangePassword.cshtml
@model eHRMS.Areas.Admin.Models.ChangePassword
@{
    ViewBag.Title = "Change Password";
    ViewBag.Now = "Settings / Change Password";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml";
}
@if (ViewBag.SuccessMsg != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Well done!</strong> @ViewBag.SuccessMsg
    </div>
}
@if (ViewBag.ErrorMsg != null)
{
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Oh snap!</strong> @ViewBag.ErrorMsg
    </div>
}
@using (Html.BeginForm("ChangePassword", "AdminAccount", FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        @*<a href="#" class="fa fa-caret-down"></a>*@
                        <!--<a href="#" class="fa fa-times"></a>-->
                    </div>
                    <h2 class="panel-title">Change Password</h2>
                </header>
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Username <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-user"></i></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.UserID, new { @class = "form-control", @placeholder = "Username", @disabled = "disabled" })
                                    @*<input type="text" class="form-control" placeholder="Username">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Current Password <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-key"></i></span>
                                    </span>
                                    @Html.PasswordFor(m => m.CurrentPassword, new { @class = "form-control", @placeholder = "Current Password" })
                                    @*<input type="password" class="form-control" placeholder="Current Password">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">New Password <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-lock"></i></span>
                                    </span>
                                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Enter New Password" })
                                    @*<input type="password" class="form-control" placeholder="Enter New Password">*@
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Confirm New Password <span style="color:#E04B4A;">*</span></label>
                            <div class="col-md-6">
                                <div class="input-group input-group-icon">
                                    <span class="input-group-addon">
                                        <span class="icon"><i class="fa fa-lock"></i></span>
                                    </span>
                                    @Html.PasswordFor(m => m.Confirm_Password , new { @class = "form-control", @placeholder = "Confirm New Password" })
                                    @*<input type="password" class="form-control" placeholder="Enter New Password">*@
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <footer class="panel-footer center">
                    <button type="submit" class="mb-xs mt-xs mr-xs btn btn-success">Submit</button>
                </footer>
            </section>
        </div>
    </div>
}